sudo: false

language: node_js
node_js:
  - stable

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  # install dependencies
  - npm install

script:
  - npm run test
  - npm run lint
